import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <div id='app'>
      <Head>
        <title>NextJS + Typescript</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
